#端口号
server:
  port: 8004

eureka:
  instance:
    hostname: localhost #地址
  client:
    service-url:
#      向注册中心注册服务
      defaultZone: http://wsm:1@${eureka.instance.hostname}:8000/eureka

spring:
  application:
    name: wsm-config-server #服务名
  cloud:
    config:
      label: master #配置仓库的分支
      server:
        git:
          uri: https://github.com/wsm1217395196/my-study.git #配置git仓库地址
          search-paths: config #配置仓库路径
          username: 1217395196@qq.com #访问git仓库的用户名
          password: Wsm960921 #访问git仓库的用户密码






