#端口号
server:
  port: 8011

eureka:
  instance:
    hostname: localhost #地址
  client:
    service-url:
#      向注册中心注册服务
      defaultZone: http://wsm:1@${eureka.instance.hostname}:8000/eureka

spring:
  application:
    name: wsm-upms #服务名
#  mysql配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: admin
    url: jdbc:mysql://${eureka.instance.hostname}:3306/wsm-upms?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

redis:
  host: 127.0.0.1
  port: 6379

# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath:/com/study/xml/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.study.model
  global-config:
    # 逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

# 这里的配置好像是（第一种实现）：每次带token的请求都会去wsm-oauth服务(存token的地方)请求对比token是否有效，是否正确（间接的方式）。
# 第二种实现：在ResourceSeverConfig类configure方法配置resources.tokenStore(tokenStore())，
#            然后直接请求(存token的地方)对比token（直接的方式）。
#       *看自己需求用哪种方式。
#security:
#  oauth2:
#    resource:
#      id: wsm-upms
#      user-info-uri: http://localhost:8001/wsm-oauth/user/principal?clientName=${spring.application.name}
#      prefer-token-info: false

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2

#熔断器开启
feign:
  hystrix:
    enabled: true

myConfig:
  isUseSecurity: true #是否使用security权限
  projectCode: wsm_project #项目编码
  clientId: client_wsm


