#端口号
server:
  port: 8009

eureka:
  instance:
    hostname: localhost #地址
  client:
    service-url:
#      向注册中心注册服务
      defaultZone: http://wsm:1@${eureka.instance.hostname}:8000/eureka

spring:
  application:
    name: wsm-demo #服务名
#  mysql配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: admin
    url: jdbc:mysql://${eureka.instance.hostname}:3306/my-study?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

#neo4j配置
  data:
    neo4j:
      username: neo4j
      password: root
      uri: bolt://${eureka.instance.hostname}:7687

# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath:/com/study/xml/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.study.model
  global-config:
    # 逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

#熔断器开启
feign:
  hystrix:
    enabled: true

#开启指标流端点 为了url访问
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
